name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
        working-directory: ./solitaire
      - run: npm run test
        working-directory: ./solitaire
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: mikeal/npx@1.0.0
      - run: npx semantic-release
        working-directory: ./solitaire
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
