name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: Borales/actions-yarn@1.1.0
      - run: yarn
      - run: yarn test

  release:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: mikeal/npx@1.0.0
      - run: npx semantic-release
